public class Problem02 {

    public static void main(String[] args) {

        // Fibbonacci Numbers
        // Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
        // By starting with 1 and 2, the first 10 terms will be 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

        // Notes:
        // I'll use a while loop
        // I'll compare with 4M

        int prev = 1;
        int previousPrev = 0;
        int sum = 0;

        while (prev < 4000000) { 
            
            int number = prev + previousPrev;

            if(number % 2 == 0){
                sum += number;
            }

            previousPrev = prev;
            prev = number;
        }

        System.out.println("Sum: " + sum);


    }
}